package proto;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/java/proto/WeatherStatusMessage.proto

public final class WeatherStatusMessageOuterClass {
  private WeatherStatusMessageOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface weatherInformationOrBuilder extends
      // @@protoc_insertion_point(interface_extends:weatherInformation)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int32 humidity = 1;</code>
     */
    int getHumidity();

    /**
     * <code>optional int32 temperature = 2;</code>
     */
    int getTemperature();

    /**
     * <code>optional int32 wind_speed = 3;</code>
     */
    int getWindSpeed();
  }
  /**
   * Protobuf type {@code weatherInformation}
   */
  public  static final class weatherInformation extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:weatherInformation)
      weatherInformationOrBuilder {
    // Use weatherInformation.newBuilder() to construct.
    private weatherInformation(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private weatherInformation() {
      humidity_ = 0;
      temperature_ = 0;
      windSpeed_ = 0;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private weatherInformation(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              humidity_ = input.readInt32();
              break;
            }
            case 16: {

              temperature_ = input.readInt32();
              break;
            }
            case 24: {

              windSpeed_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return WeatherStatusMessageOuterClass.internal_static_weatherInformation_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return WeatherStatusMessageOuterClass.internal_static_weatherInformation_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              weatherInformation.class, Builder.class);
    }

    public static final int HUMIDITY_FIELD_NUMBER = 1;
    private int humidity_;
    /**
     * <code>optional int32 humidity = 1;</code>
     */
    public int getHumidity() {
      return humidity_;
    }

    public static final int TEMPERATURE_FIELD_NUMBER = 2;
    private int temperature_;
    /**
     * <code>optional int32 temperature = 2;</code>
     */
    public int getTemperature() {
      return temperature_;
    }

    public static final int WIND_SPEED_FIELD_NUMBER = 3;
    private int windSpeed_;
    /**
     * <code>optional int32 wind_speed = 3;</code>
     */
    public int getWindSpeed() {
      return windSpeed_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (humidity_ != 0) {
        output.writeInt32(1, humidity_);
      }
      if (temperature_ != 0) {
        output.writeInt32(2, temperature_);
      }
      if (windSpeed_ != 0) {
        output.writeInt32(3, windSpeed_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (humidity_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, humidity_);
      }
      if (temperature_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, temperature_);
      }
      if (windSpeed_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, windSpeed_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof weatherInformation)) {
        return super.equals(obj);
      }
      weatherInformation other = (weatherInformation) obj;

      boolean result = true;
      result = result && (getHumidity()
          == other.getHumidity());
      result = result && (getTemperature()
          == other.getTemperature());
      result = result && (getWindSpeed()
          == other.getWindSpeed());
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + HUMIDITY_FIELD_NUMBER;
      hash = (53 * hash) + getHumidity();
      hash = (37 * hash) + TEMPERATURE_FIELD_NUMBER;
      hash = (53 * hash) + getTemperature();
      hash = (37 * hash) + WIND_SPEED_FIELD_NUMBER;
      hash = (53 * hash) + getWindSpeed();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static weatherInformation parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static weatherInformation parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static weatherInformation parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static weatherInformation parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static weatherInformation parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static weatherInformation parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static weatherInformation parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static weatherInformation parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static weatherInformation parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static weatherInformation parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(weatherInformation prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code weatherInformation}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:weatherInformation)
        weatherInformationOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return WeatherStatusMessageOuterClass.internal_static_weatherInformation_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return WeatherStatusMessageOuterClass.internal_static_weatherInformation_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                weatherInformation.class, Builder.class);
      }

      // Construct using WeatherStatusMessageOuterClass.weatherInformation.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        humidity_ = 0;

        temperature_ = 0;

        windSpeed_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return WeatherStatusMessageOuterClass.internal_static_weatherInformation_descriptor;
      }

      public weatherInformation getDefaultInstanceForType() {
        return weatherInformation.getDefaultInstance();
      }

      public weatherInformation build() {
        weatherInformation result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public weatherInformation buildPartial() {
        weatherInformation result = new weatherInformation(this);
        result.humidity_ = humidity_;
        result.temperature_ = temperature_;
        result.windSpeed_ = windSpeed_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof weatherInformation) {
          return mergeFrom((weatherInformation)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(weatherInformation other) {
        if (other == weatherInformation.getDefaultInstance()) return this;
        if (other.getHumidity() != 0) {
          setHumidity(other.getHumidity());
        }
        if (other.getTemperature() != 0) {
          setTemperature(other.getTemperature());
        }
        if (other.getWindSpeed() != 0) {
          setWindSpeed(other.getWindSpeed());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        weatherInformation parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (weatherInformation) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int humidity_ ;
      /**
       * <code>optional int32 humidity = 1;</code>
       */
      public int getHumidity() {
        return humidity_;
      }
      /**
       * <code>optional int32 humidity = 1;</code>
       */
      public Builder setHumidity(int value) {
        
        humidity_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 humidity = 1;</code>
       */
      public Builder clearHumidity() {
        
        humidity_ = 0;
        onChanged();
        return this;
      }

      private int temperature_ ;
      /**
       * <code>optional int32 temperature = 2;</code>
       */
      public int getTemperature() {
        return temperature_;
      }
      /**
       * <code>optional int32 temperature = 2;</code>
       */
      public Builder setTemperature(int value) {
        
        temperature_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 temperature = 2;</code>
       */
      public Builder clearTemperature() {
        
        temperature_ = 0;
        onChanged();
        return this;
      }

      private int windSpeed_ ;
      /**
       * <code>optional int32 wind_speed = 3;</code>
       */
      public int getWindSpeed() {
        return windSpeed_;
      }
      /**
       * <code>optional int32 wind_speed = 3;</code>
       */
      public Builder setWindSpeed(int value) {
        
        windSpeed_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 wind_speed = 3;</code>
       */
      public Builder clearWindSpeed() {
        
        windSpeed_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:weatherInformation)
    }

    // @@protoc_insertion_point(class_scope:weatherInformation)
    private static final weatherInformation DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new weatherInformation();
    }

    public static weatherInformation getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<weatherInformation>
        PARSER = new com.google.protobuf.AbstractParser<weatherInformation>() {
      public weatherInformation parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new weatherInformation(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<weatherInformation> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<weatherInformation> getParserForType() {
      return PARSER;
    }

    public weatherInformation getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface WeatherStatusMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:WeatherStatusMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional int64 station_id = 1;</code>
     */
    long getStationId();

    /**
     * <code>optional string battery_status = 2;</code>
     */
    String getBatteryStatus();
    /**
     * <code>optional string battery_status = 2;</code>
     */
    com.google.protobuf.ByteString
        getBatteryStatusBytes();

    /**
     * <code>optional .weatherInformation weatherInfo = 3;</code>
     */
    boolean hasWeatherInfo();
    /**
     * <code>optional .weatherInformation weatherInfo = 3;</code>
     */
    weatherInformation getWeatherInfo();
    /**
     * <code>optional .weatherInformation weatherInfo = 3;</code>
     */
    weatherInformationOrBuilder getWeatherInfoOrBuilder();

    /**
     * <code>optional int64 s_no = 4;</code>
     */
    long getSNo();

    /**
     * <code>optional int64 status_timestamp = 5;</code>
     */
    long getStatusTimestamp();
  }
  /**
   * Protobuf type {@code WeatherStatusMessage}
   */
  public  static final class WeatherStatusMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:WeatherStatusMessage)
      WeatherStatusMessageOrBuilder {
    // Use WeatherStatusMessage.newBuilder() to construct.
    private WeatherStatusMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private WeatherStatusMessage() {
      stationId_ = 0L;
      batteryStatus_ = "";
      sNo_ = 0L;
      statusTimestamp_ = 0L;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private WeatherStatusMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              stationId_ = input.readInt64();
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              batteryStatus_ = s;
              break;
            }
            case 26: {
              weatherInformation.Builder subBuilder = null;
              if (weatherInfo_ != null) {
                subBuilder = weatherInfo_.toBuilder();
              }
              weatherInfo_ = input.readMessage(weatherInformation.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(weatherInfo_);
                weatherInfo_ = subBuilder.buildPartial();
              }

              break;
            }
            case 32: {

              sNo_ = input.readInt64();
              break;
            }
            case 40: {

              statusTimestamp_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return WeatherStatusMessageOuterClass.internal_static_WeatherStatusMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return WeatherStatusMessageOuterClass.internal_static_WeatherStatusMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              WeatherStatusMessage.class, Builder.class);
    }

    public static final int STATION_ID_FIELD_NUMBER = 1;
    private long stationId_;
    /**
     * <code>optional int64 station_id = 1;</code>
     */
    public long getStationId() {
      return stationId_;
    }

    public static final int BATTERY_STATUS_FIELD_NUMBER = 2;
    private volatile Object batteryStatus_;
    /**
     * <code>optional string battery_status = 2;</code>
     */
    public String getBatteryStatus() {
      Object ref = batteryStatus_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        batteryStatus_ = s;
        return s;
      }
    }
    /**
     * <code>optional string battery_status = 2;</code>
     */
    public com.google.protobuf.ByteString
        getBatteryStatusBytes() {
      Object ref = batteryStatus_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        batteryStatus_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int WEATHERINFO_FIELD_NUMBER = 3;
    private weatherInformation weatherInfo_;
    /**
     * <code>optional .weatherInformation weatherInfo = 3;</code>
     */
    public boolean hasWeatherInfo() {
      return weatherInfo_ != null;
    }
    /**
     * <code>optional .weatherInformation weatherInfo = 3;</code>
     */
    public weatherInformation getWeatherInfo() {
      return weatherInfo_ == null ? weatherInformation.getDefaultInstance() : weatherInfo_;
    }
    /**
     * <code>optional .weatherInformation weatherInfo = 3;</code>
     */
    public weatherInformationOrBuilder getWeatherInfoOrBuilder() {
      return getWeatherInfo();
    }

    public static final int S_NO_FIELD_NUMBER = 4;
    private long sNo_;
    /**
     * <code>optional int64 s_no = 4;</code>
     */
    public long getSNo() {
      return sNo_;
    }

    public static final int STATUS_TIMESTAMP_FIELD_NUMBER = 5;
    private long statusTimestamp_;
    /**
     * <code>optional int64 status_timestamp = 5;</code>
     */
    public long getStatusTimestamp() {
      return statusTimestamp_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (stationId_ != 0L) {
        output.writeInt64(1, stationId_);
      }
      if (!getBatteryStatusBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, batteryStatus_);
      }
      if (weatherInfo_ != null) {
        output.writeMessage(3, getWeatherInfo());
      }
      if (sNo_ != 0L) {
        output.writeInt64(4, sNo_);
      }
      if (statusTimestamp_ != 0L) {
        output.writeInt64(5, statusTimestamp_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (stationId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, stationId_);
      }
      if (!getBatteryStatusBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, batteryStatus_);
      }
      if (weatherInfo_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getWeatherInfo());
      }
      if (sNo_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, sNo_);
      }
      if (statusTimestamp_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, statusTimestamp_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof WeatherStatusMessage)) {
        return super.equals(obj);
      }
      WeatherStatusMessage other = (WeatherStatusMessage) obj;

      boolean result = true;
      result = result && (getStationId()
          == other.getStationId());
      result = result && getBatteryStatus()
          .equals(other.getBatteryStatus());
      result = result && (hasWeatherInfo() == other.hasWeatherInfo());
      if (hasWeatherInfo()) {
        result = result && getWeatherInfo()
            .equals(other.getWeatherInfo());
      }
      result = result && (getSNo()
          == other.getSNo());
      result = result && (getStatusTimestamp()
          == other.getStatusTimestamp());
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + STATION_ID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getStationId());
      hash = (37 * hash) + BATTERY_STATUS_FIELD_NUMBER;
      hash = (53 * hash) + getBatteryStatus().hashCode();
      if (hasWeatherInfo()) {
        hash = (37 * hash) + WEATHERINFO_FIELD_NUMBER;
        hash = (53 * hash) + getWeatherInfo().hashCode();
      }
      hash = (37 * hash) + S_NO_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getSNo());
      hash = (37 * hash) + STATUS_TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getStatusTimestamp());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static WeatherStatusMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static WeatherStatusMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static WeatherStatusMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static WeatherStatusMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static WeatherStatusMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static WeatherStatusMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static WeatherStatusMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static WeatherStatusMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static WeatherStatusMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static WeatherStatusMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(WeatherStatusMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code WeatherStatusMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:WeatherStatusMessage)
        WeatherStatusMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return WeatherStatusMessageOuterClass.internal_static_WeatherStatusMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return WeatherStatusMessageOuterClass.internal_static_WeatherStatusMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                WeatherStatusMessage.class, Builder.class);
      }

      // Construct using WeatherStatusMessageOuterClass.WeatherStatusMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        stationId_ = 0L;

        batteryStatus_ = "";

        if (weatherInfoBuilder_ == null) {
          weatherInfo_ = null;
        } else {
          weatherInfo_ = null;
          weatherInfoBuilder_ = null;
        }
        sNo_ = 0L;

        statusTimestamp_ = 0L;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return WeatherStatusMessageOuterClass.internal_static_WeatherStatusMessage_descriptor;
      }

      public WeatherStatusMessage getDefaultInstanceForType() {
        return WeatherStatusMessage.getDefaultInstance();
      }

      public WeatherStatusMessage build() {
        WeatherStatusMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public WeatherStatusMessage buildPartial() {
        WeatherStatusMessage result = new WeatherStatusMessage(this);
        result.stationId_ = stationId_;
        result.batteryStatus_ = batteryStatus_;
        if (weatherInfoBuilder_ == null) {
          result.weatherInfo_ = weatherInfo_;
        } else {
          result.weatherInfo_ = weatherInfoBuilder_.build();
        }
        result.sNo_ = sNo_;
        result.statusTimestamp_ = statusTimestamp_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof WeatherStatusMessage) {
          return mergeFrom((WeatherStatusMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(WeatherStatusMessage other) {
        if (other == WeatherStatusMessage.getDefaultInstance()) return this;
        if (other.getStationId() != 0L) {
          setStationId(other.getStationId());
        }
        if (!other.getBatteryStatus().isEmpty()) {
          batteryStatus_ = other.batteryStatus_;
          onChanged();
        }
        if (other.hasWeatherInfo()) {
          mergeWeatherInfo(other.getWeatherInfo());
        }
        if (other.getSNo() != 0L) {
          setSNo(other.getSNo());
        }
        if (other.getStatusTimestamp() != 0L) {
          setStatusTimestamp(other.getStatusTimestamp());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        WeatherStatusMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (WeatherStatusMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private long stationId_ ;
      /**
       * <code>optional int64 station_id = 1;</code>
       */
      public long getStationId() {
        return stationId_;
      }
      /**
       * <code>optional int64 station_id = 1;</code>
       */
      public Builder setStationId(long value) {
        
        stationId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 station_id = 1;</code>
       */
      public Builder clearStationId() {
        
        stationId_ = 0L;
        onChanged();
        return this;
      }

      private Object batteryStatus_ = "";
      /**
       * <code>optional string battery_status = 2;</code>
       */
      public String getBatteryStatus() {
        Object ref = batteryStatus_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          batteryStatus_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string battery_status = 2;</code>
       */
      public com.google.protobuf.ByteString
          getBatteryStatusBytes() {
        Object ref = batteryStatus_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          batteryStatus_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string battery_status = 2;</code>
       */
      public Builder setBatteryStatus(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        batteryStatus_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string battery_status = 2;</code>
       */
      public Builder clearBatteryStatus() {
        
        batteryStatus_ = getDefaultInstance().getBatteryStatus();
        onChanged();
        return this;
      }
      /**
       * <code>optional string battery_status = 2;</code>
       */
      public Builder setBatteryStatusBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        batteryStatus_ = value;
        onChanged();
        return this;
      }

      private weatherInformation weatherInfo_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          weatherInformation, weatherInformation.Builder, weatherInformationOrBuilder> weatherInfoBuilder_;
      /**
       * <code>optional .weatherInformation weatherInfo = 3;</code>
       */
      public boolean hasWeatherInfo() {
        return weatherInfoBuilder_ != null || weatherInfo_ != null;
      }
      /**
       * <code>optional .weatherInformation weatherInfo = 3;</code>
       */
      public weatherInformation getWeatherInfo() {
        if (weatherInfoBuilder_ == null) {
          return weatherInfo_ == null ? weatherInformation.getDefaultInstance() : weatherInfo_;
        } else {
          return weatherInfoBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .weatherInformation weatherInfo = 3;</code>
       */
      public Builder setWeatherInfo(weatherInformation value) {
        if (weatherInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          weatherInfo_ = value;
          onChanged();
        } else {
          weatherInfoBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>optional .weatherInformation weatherInfo = 3;</code>
       */
      public Builder setWeatherInfo(
          weatherInformation.Builder builderForValue) {
        if (weatherInfoBuilder_ == null) {
          weatherInfo_ = builderForValue.build();
          onChanged();
        } else {
          weatherInfoBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>optional .weatherInformation weatherInfo = 3;</code>
       */
      public Builder mergeWeatherInfo(weatherInformation value) {
        if (weatherInfoBuilder_ == null) {
          if (weatherInfo_ != null) {
            weatherInfo_ =
              weatherInformation.newBuilder(weatherInfo_).mergeFrom(value).buildPartial();
          } else {
            weatherInfo_ = value;
          }
          onChanged();
        } else {
          weatherInfoBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>optional .weatherInformation weatherInfo = 3;</code>
       */
      public Builder clearWeatherInfo() {
        if (weatherInfoBuilder_ == null) {
          weatherInfo_ = null;
          onChanged();
        } else {
          weatherInfo_ = null;
          weatherInfoBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>optional .weatherInformation weatherInfo = 3;</code>
       */
      public weatherInformation.Builder getWeatherInfoBuilder() {
        
        onChanged();
        return getWeatherInfoFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .weatherInformation weatherInfo = 3;</code>
       */
      public weatherInformationOrBuilder getWeatherInfoOrBuilder() {
        if (weatherInfoBuilder_ != null) {
          return weatherInfoBuilder_.getMessageOrBuilder();
        } else {
          return weatherInfo_ == null ?
              weatherInformation.getDefaultInstance() : weatherInfo_;
        }
      }
      /**
       * <code>optional .weatherInformation weatherInfo = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          weatherInformation, weatherInformation.Builder, weatherInformationOrBuilder>
          getWeatherInfoFieldBuilder() {
        if (weatherInfoBuilder_ == null) {
          weatherInfoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              weatherInformation, weatherInformation.Builder, weatherInformationOrBuilder>(
                  getWeatherInfo(),
                  getParentForChildren(),
                  isClean());
          weatherInfo_ = null;
        }
        return weatherInfoBuilder_;
      }

      private long sNo_ ;
      /**
       * <code>optional int64 s_no = 4;</code>
       */
      public long getSNo() {
        return sNo_;
      }
      /**
       * <code>optional int64 s_no = 4;</code>
       */
      public Builder setSNo(long value) {
        
        sNo_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 s_no = 4;</code>
       */
      public Builder clearSNo() {
        
        sNo_ = 0L;
        onChanged();
        return this;
      }

      private long statusTimestamp_ ;
      /**
       * <code>optional int64 status_timestamp = 5;</code>
       */
      public long getStatusTimestamp() {
        return statusTimestamp_;
      }
      /**
       * <code>optional int64 status_timestamp = 5;</code>
       */
      public Builder setStatusTimestamp(long value) {
        
        statusTimestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 status_timestamp = 5;</code>
       */
      public Builder clearStatusTimestamp() {
        
        statusTimestamp_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:WeatherStatusMessage)
    }

    // @@protoc_insertion_point(class_scope:WeatherStatusMessage)
    private static final WeatherStatusMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new WeatherStatusMessage();
    }

    public static WeatherStatusMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<WeatherStatusMessage>
        PARSER = new com.google.protobuf.AbstractParser<WeatherStatusMessage>() {
      public WeatherStatusMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new WeatherStatusMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<WeatherStatusMessage> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<WeatherStatusMessage> getParserForType() {
      return PARSER;
    }

    public WeatherStatusMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_weatherInformation_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_weatherInformation_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_WeatherStatusMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_WeatherStatusMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n.src/main/java/proto/WeatherStatusMessa" +
      "ge.proto\"O\n\022weatherInformation\022\020\n\010humidi" +
      "ty\030\001 \001(\005\022\023\n\013temperature\030\002 \001(\005\022\022\n\nwind_sp" +
      "eed\030\003 \001(\005\"\224\001\n\024WeatherStatusMessage\022\022\n\nst" +
      "ation_id\030\001 \001(\003\022\026\n\016battery_status\030\002 \001(\t\022(" +
      "\n\013weatherInfo\030\003 \001(\0132\023.weatherInformation" +
      "\022\014\n\004s_no\030\004 \001(\003\022\030\n\020status_timestamp\030\005 \001(\003" +
      "b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_weatherInformation_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_weatherInformation_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_weatherInformation_descriptor,
        new String[] { "Humidity", "Temperature", "WindSpeed", });
    internal_static_WeatherStatusMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_WeatherStatusMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_WeatherStatusMessage_descriptor,
        new String[] { "StationId", "BatteryStatus", "WeatherInfo", "SNo", "StatusTimestamp", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
